### ISSUE TITLE
Efp animation shaking

### ISSUE THREAD

**Issue by GenomeDeveloper** [JellyBitz/JMX-File-Editor#4]
when i change color to map object efp file animation shaking even i wont change anything only open file and save ,color its changing and animation start to shaking you can try Particles|map\yellow_oura_b.efp this efp file belong Data|res\mob\season\sc_magic_tower.bsr

**Comment by JellyBitz** [comment]
I'm sorry, I didn't test this file format enough since I'm not editing effects. I just added support to edit them from @DummkopfOfHachtenduden contribution (https://github.com/DummkopfOfHachtenduden/SilkroadDoc/wiki/JMXVEFF).

I had a similar report by the way. What I found comparing byte to byte (I mean, old with new file generated) it's the version, because it will be upgraded to the latest version (`JMXVEFF 0013`) on saving.
Maybe that plays a role on how the client execute it? I don't really know, maybe in a future.

**Comment by JellyBitz** [comment]
I've been working around .efp files, editing colors and some stuffs without experiencing any bug.

However the EFP file you mentioned was using an unnexpected value type, probably causing the issue you mentioned. Now the file export identical file but just the version in general upgraded.
